/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2017 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void *init_proc();
int sub_80484D0();
// int printf(const char *format, ...);
// void free(void *ptr);
// char *fgets(char *s, int n, FILE *stream);
// unsigned int alarm(unsigned int seconds);
// void *malloc(size_t size);
// int puts(const char *s);
// void exit(int status);
// char *strchr(const char *s, int c);
// int setvbuf(FILE *stream, char *buf, int modes, size_t n);
// void *memset(void *s, int c, size_t n);
// int __isoc99_scanf(const char *, ...); weak
// int _gmon_start__(void); weak
void sub_80485F0();
int sub_8048600();
int sub_8048670();
int sub_8048690();
unsigned int __cdecl sub_80486BB(char *a1, int a2);
unsigned int __cdecl sub_8048724(unsigned __int8 a1);
_DWORD *__cdecl sub_8048816(size_t a1);
unsigned int __cdecl sub_8048905(unsigned __int8 a1);
unsigned int __cdecl sub_804898F(unsigned __int8 a1);
void __cdecl __noreturn main();
void init(void); // idb
void term_proc();

//-------------------------------------------------------------------------
// Data declarations

int (*off_804AF08[2])() = { &sub_8048690, &sub_8048670 }; // weak
int (*off_804AF0C)() = &sub_8048670; // weak
int (*dword_804B008)(void) = NULL; // weak
_UNKNOWN unk_804B048; // weak
_UNKNOWN unk_804B04B; // weak
FILE *stdin; // idb
FILE *stdout; // idb
char byte_804B068; // weak
char byte_804B069; // weak
void *ptr[50]; // idb
// extern _UNKNOWN __gmon_start__; weak


//----- (080484A4) --------------------------------------------------------
void *init_proc()
{
  void *result; // eax

  result = &__gmon_start__;
  if ( &__gmon_start__ )
    result = (void *)_gmon_start__();
  return result;
}
// 80485B0: using guessed type int _gmon_start__(void);

//----- (080484D0) --------------------------------------------------------
int sub_80484D0()
{
  return dword_804B008();
}
// 804B008: using guessed type int (*dword_804B008)(void);

//----- (080485C0) --------------------------------------------------------
#error "80485C3: positive sp value has been found (funcsize=2)"

//----- (080485F0) --------------------------------------------------------
void sub_80485F0()
{
  ;
}

//----- (08048600) --------------------------------------------------------
int sub_8048600()
{
  int result; // eax

  result = &unk_804B04B - &unk_804B048;
  if ( (unsigned int)(&unk_804B04B - &unk_804B048) > 6 )
    result = 0;
  return result;
}
// 8048600: could not find valid save-restore pair for ebp

//----- (08048670) --------------------------------------------------------
int sub_8048670()
{
  int result; // eax

  if ( !byte_804B068 )
  {
    result = sub_8048600();
    byte_804B068 = 1;
  }
  return result;
}
// 8048670: could not find valid save-restore pair for ebp
// 804B068: using guessed type char byte_804B068;

//----- (08048690) --------------------------------------------------------
int sub_8048690()
{
  return 0;
}
// 8048690: could not find valid save-restore pair for ebp

//----- (080486BB) --------------------------------------------------------
unsigned int __cdecl sub_80486BB(char *a1, int a2)
{
  char *v3; // [esp+18h] [ebp-10h]
  unsigned int v4; // [esp+1Ch] [ebp-Ch]

  v4 = __readgsdword(0x14u);
  fgets(a1, a2, stdin);
  v3 = strchr(a1, 10);
  if ( v3 )
    *v3 = 0;
  return __readgsdword(0x14u) ^ v4;
}

//----- (08048724) --------------------------------------------------------
unsigned int __cdecl sub_8048724(unsigned __int8 a1)
{
  char v2; // [esp+17h] [ebp-11h]
  int v3; // [esp+18h] [ebp-10h]
  unsigned int v4; // [esp+1Ch] [ebp-Ch]

  v4 = __readgsdword(0x14u);
  if ( a1 < (unsigned __int8)byte_804B069 && ptr[a1] )
  {
    v3 = 0;
    printf("text length: ");
    __isoc99_scanf("%u%c", &v3, &v2);
    if ( (char *)(v3 + *(_DWORD *)ptr[a1]) >= (char *)ptr[a1] - 4 )
    {
      puts("my l33t defenses cannot be fooled, cya!");
      exit(1);
    }
    printf("text: ");
    sub_80486BB(*(char **)ptr[a1], v3 + 1);
  }
  return __readgsdword(0x14u) ^ v4;
}
// 80485A0: using guessed type int __isoc99_scanf(const char *, ...);
// 804B069: using guessed type char byte_804B069;

//----- (08048816) --------------------------------------------------------
_DWORD *__cdecl sub_8048816(size_t a1)
{
  void *s; // ST24_4
  _DWORD *v2; // ST28_4

  s = malloc(a1);
  memset(s, 0, a1);
  v2 = malloc(0x80u);
  memset(v2, 0, 0x80u);
  *v2 = s;
  ptr[(unsigned __int8)byte_804B069] = v2;
  printf("name: ");
  sub_80486BB((char *)ptr[(unsigned __int8)byte_804B069] + 4, 124);
  sub_8048724(++byte_804B069 - 1);
  return v2;
}
// 804B069: using guessed type char byte_804B069;

//----- (08048905) --------------------------------------------------------
unsigned int __cdecl sub_8048905(unsigned __int8 a1)
{
  unsigned int v2; // [esp+1Ch] [ebp-Ch]

  v2 = __readgsdword(0x14u);
  if ( a1 < (unsigned __int8)byte_804B069 && ptr[a1] )
  {
    free(*(void **)ptr[a1]);
    free(ptr[a1]);
    ptr[a1] = 0;
  }
  return __readgsdword(0x14u) ^ v2;
}
// 804B069: using guessed type char byte_804B069;

//----- (0804898F) --------------------------------------------------------
unsigned int __cdecl sub_804898F(unsigned __int8 a1)
{
  unsigned int v2; // [esp+1Ch] [ebp-Ch]

  v2 = __readgsdword(0x14u);
  if ( a1 < (unsigned __int8)byte_804B069 && ptr[a1] )
  {
    printf("name: %s\n", (char *)ptr[a1] + 4);
    printf("description: %s\n", *(_DWORD *)ptr[a1]);
  }
  return __readgsdword(0x14u) ^ v2;
}
// 804B069: using guessed type char byte_804B069;

//----- (08048A17) --------------------------------------------------------
void __cdecl __noreturn main()
{
  char v0; // [esp+3h] [ebp-15h]
  int v1; // [esp+4h] [ebp-14h]
  size_t v2; // [esp+8h] [ebp-10h]
  unsigned int v3; // [esp+Ch] [ebp-Ch]

  v3 = __readgsdword(0x14u);
  setvbuf(stdin, 0, 2, 0);
  setvbuf(stdout, 0, 2, 0);
  alarm(0x14u);
  while ( 1 )
  {
    puts("0: Add a user");
    puts("1: Delete a user");
    puts("2: Display a user");
    puts("3: Update a user description");
    puts("4: Exit");
    printf("Action: ");
    if ( __isoc99_scanf("%d", &v1) == -1 )
      break;
    if ( !v1 )
    {
      printf("size of description: ");
      __isoc99_scanf("%u%c", &v2, &v0);
      sub_8048816(v2);
    }
    if ( v1 == 1 )
    {
      printf("index: ");
      __isoc99_scanf("%d", &v2);
      sub_8048905(v2);
    }
    if ( v1 == 2 )
    {
      printf("index: ");
      __isoc99_scanf("%d", &v2);
      sub_804898F(v2);
    }
    if ( v1 == 3 )
    {
      printf("index: ");
      __isoc99_scanf("%d", &v2);
      sub_8048724(v2);
    }
    if ( v1 == 4 )
    {
      puts("Bye");
      exit(0);
    }
    if ( (unsigned __int8)byte_804B069 > 0x31u )
    {
      puts("maximum capacity exceeded, bye");
      exit(0);
    }
  }
  exit(1);
}
// 80485A0: using guessed type int __isoc99_scanf(const char *, ...);
// 804B069: using guessed type char byte_804B069;

//----- (08048C30) --------------------------------------------------------
void init(void)
{
  int v0; // esi
  int v1; // edi

  init_proc();
  v0 = &off_804AF0C - off_804AF08;
  if ( v0 )
  {
    v1 = 0;
    do
      off_804AF08[v1++]();
    while ( v1 != v0 );
  }
}
// 804AF08: using guessed type int (*off_804AF08[2])();
// 804AF0C: using guessed type int (*off_804AF0C)();

//----- (08048C94) --------------------------------------------------------
void term_proc()
{
  ;
}

#error "There were 1 decompilation failure(s) on 15 function(s)"
