/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2016 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void *init_proc();
// void __noreturn _exit(int status);
// int puts(const char *s);
// void setbuf(FILE *stream, char *buf);
// void *memset(void *s, int c, size_t n);
// __int64 __gmon_start__(void); weak
// int _IO_getc(_IO_FILE *fp);
// __int64 __fastcall __printf_chk(_QWORD, _QWORD); weak
// __int64 __fastcall _IO_gets(_QWORD); weak
__int64 __fastcall main(__int64 a1, char **a2, char **a3);
signed __int64 sub_400720();
__int64 sub_400750();
signed __int64 sub_400790();
__int64 sub_4007B0();
__int64 sub_4007E0();
void __fastcall init(unsigned int a1, __int64 a2, __int64 a3);
void term_proc();

//-------------------------------------------------------------------------
// Data declarations

__int64 (__fastcall *off_600AA0[2])() = { &sub_4007B0, &sub_400790 }; // weak
__int64 (__fastcall *off_600AA8)() = &sub_400790; // weak
char byte_600D20[] = { '3' }; // weak
FILE *stdout; // idb
_IO_FILE *stdin; // idb
char byte_600D50; // weak
// extern _UNKNOWN _gmon_start__; weak


//----- (00000000004005F8) ----------------------------------------------------
void *init_proc()
{
  void *result; // rax@1

  result = &_gmon_start__;
  if ( &_gmon_start__ )
    result = (void *)__gmon_start__();
  return result;
}
// 400690: using guessed type __int64 __gmon_start__(void);

//----- (00000000004006D0) ----------------------------------------------------
__int64 __fastcall main(__int64 a1, char **a2, char **a3)
{
  setbuf(stdout, 0LL);
  sub_4007E0();
  return 0LL;
}

//----- (00000000004006EE) ----------------------------------------------------
#error "4006F4: positive sp value has been found (funcsize=3)"

//----- (0000000000400720) ----------------------------------------------------
signed __int64 sub_400720()
{
  signed __int64 result; // rax@1

  result = 6294855LL - (_QWORD)&stdout;
  if ( (unsigned __int64)(6294855LL - (_QWORD)&stdout) > 0xE )
    result = 0LL;
  return result;
}

//----- (0000000000400750) ----------------------------------------------------
__int64 sub_400750()
{
  return 0LL;
}

//----- (0000000000400790) ----------------------------------------------------
signed __int64 sub_400790()
{
  signed __int64 result; // rax@2

  if ( !byte_600D50 )
  {
    result = sub_400720();
    byte_600D50 = 1;
  }
  return result;
}
// 600D50: using guessed type char byte_600D50;

//----- (00000000004007B0) ----------------------------------------------------
__int64 sub_4007B0()
{
  return sub_400750();
}
// 4007B0: could not find valid save-restore pair for rbp

//----- (00000000004007E0) ----------------------------------------------------
__int64 sub_4007E0()
{
  __int64 v0; // rbx@2
  int v1; // eax@3
  __int64 v3; // [rsp+0h] [rbp-128h]@1
  __int64 v4; // [rsp+108h] [rbp-20h]@1

  v4 = *MK_FP(__FS__, 40LL);
  __printf_chk(1LL, "Hello!\nWhat's your name? ");
  if ( !_IO_gets(&v3) )
LABEL_9:
    _exit(1);
  v0 = 0LL;
  __printf_chk(1LL, "Nice to meet you, %s.\nPlease overwrite the flag: ");
  while ( 1 )
  {
    v1 = _IO_getc(stdin);
    if ( v1 == -1 )
      goto LABEL_9;
    if ( v1 == 10 )
      break;
    byte_600D20[v0++] = v1;
    if ( v0 == 32 )
      goto LABEL_8;
  }
  memset((void *)((signed int)v0 + 6294816LL), 0, (unsigned int)(32 - v0));
LABEL_8:
  puts("Thank you, bye!");
  return *MK_FP(__FS__, 40LL) ^ v4;
}
// 4006B0: using guessed type __int64 __fastcall __printf_chk(_QWORD, _QWORD);
// 4006C0: using guessed type __int64 __fastcall _IO_gets(_QWORD);

//----- (00000000004008B0) ----------------------------------------------------
void __fastcall init(unsigned int a1, __int64 a2, __int64 a3)
{
  __int64 v3; // r13@1
  __int64 v4; // rbx@1
  signed __int64 v5; // rbp@1

  v3 = a3;
  v4 = 0LL;
  v5 = &off_600AA8 - off_600AA0;
  init_proc();
  if ( v5 )
  {
    do
      ((void (__fastcall *)(_QWORD, __int64, __int64))off_600AA0[v4++])(a1, a2, v3);
    while ( v4 != v5 );
  }
}
// 600AA0: using guessed type __int64 (__fastcall *off_600AA0[2])();
// 600AA8: using guessed type __int64 (__fastcall *off_600AA8)();

//----- (0000000000400924) ----------------------------------------------------
void term_proc()
{
  ;
}

#error "There were 1 decompilation failure(s) on 10 function(s)"
