/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2016 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

// void __noreturn _exit(int status);
// int puts(const char *s);
// void *mmap(void *addr, size_t len, int prot, int flags, int fd, __off_t offset);
// ssize_t read(int fd, void *buf, size_t nbytes);
// int fflush(FILE *stream);
// int mprotect(void *addr, size_t len, int prot);
void __noreturn start();
int sub_4004E6();

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN loc_4004DE; // weak


//----- (0000000000400480) ----------------------------------------------------
void __noreturn start()
{
  char *v0; // rax@1
  __int64 v1; // rax@2

  v0 = (char *)mmap(0LL, 0x3000uLL, 0, 34, 0, 0LL);
  if ( v0 != (char *)-1LL )
  {
    LODWORD(v1) = mprotect(v0 + 4096, 0x1000uLL, 3);
    if ( v1 != -1 )
    {
      while ( 1 )
        sub_4004E6();
    }
  }
  _exit(0);
}

//----- (00000000004004E6) ----------------------------------------------------
int sub_4004E6()
{
  size_t buf; // [rsp+0h] [rbp-8h]@1

  JUMPOUT(read(0, &buf, 8uLL), 0LL, &loc_4004DE);
  JUMPOUT(read(0, &buf, buf), 0LL, &loc_4004DE);
  puts((const char *)&buf);
  return fflush(0LL);
}

// ALL OK, 2 function(s) have been successfully decompiled
